### ISSUE TITLE
unexpected end of JSON input on q.parse()

### ISSUE THREAD

**Issue by ianrapha** [vbatoufflet/go-livestatus#6]
Hi,

I'm trying to use the lib but i'm getting an error. I dumped the buf.Bytes() content and the JSON is ending with a comma not the enclosing bracket.

But when i tested with unixcat (line below) using the statement, the file generation ran successfully with a 2.3MB size. 

`/path/to/unixcat < services /path/to//live >> services.csv`

The statement generated by q.buildCmd() is below.

```
GET services
Columns: host_alias display_name last_check last_check host_address description execution_time state
ResponseHeader: fixed16
OutputFormat: json
```

I didn't find any coding issue and I'm asking for help.

Thanks,
Ian Raphael

**Comment by vbatoufflet** [comment]
Hi @ianrapha,

Any chance you can provide me with the `services.csv` file (if not that sensitive)?

Which version of MKLivestatus are you using?

**Comment by ianrapha** [comment]
Hello @vbatoufflet 

Sorry, I cannot provide the content right now. I'll try to remove the sensitive parts and attach here. The file size is 106496 bytes and 915 lines.

I tested with all tables and the problem occurred only on **services** table.

The MKLs version is 1.2.8.

**Comment by ianrapha** [comment]
Probably something is happening with **OutputFormat: json**.
After commenting this line the extraction worked well.

**Comment by jleavers** [comment]
I have also noticed this problem when retrieving larger numbers of services.

Filtering for state = 0 with approx 800 results works. On a larger Nagios installation with approx 1800 results, I get "Error: unexpected end of JSON input".

Looking at the Exec() function in query.go, data is created with a length of 1024 and there is then a check for new line:

```
if data[n-1] == byte('\n') {
   break
}
```

If I temporarily change this:

```
if data[n-1] == byte('\n') {
   fmt.Printf("New line found: %d\n", n)
}
```

I then see the new line being found several times before reaching the end of the data, which is why a larger set of results is truncated, but a smaller set is okay.

```
New line found: 1024
New line found: 1024
New line found: 147
```

So as a quick workaround I changed the length of data to 10240.

**Comment by vbatoufflet** [comment]
Hi all,

Sorry for the huge delay on this. I didn't took the time to maintain this project a lot this year.

The issue is now fixed. After some additional debugging, the fact is that the problem was triggered by having `\n` exactly as the 1024th character in the middle of a Livestatus response.
